### ISSUE TITLE
Entidad no aparece

### ISSUE THREAD

**Issue by diego-de-sousa** [Danieldiazi/homeassistant-meteogalicia_tides#1]
Hola!

No me aparece la entidad de meteogalicia_tides.
La tenía instalada desde hace unos meses pero nunca llegué a probarla bien. Hoy quise comprobar y me salía como que la entidad ya no estaba disponible. Borré la entidad, volví a descargar desde HACS y ahora no tengo ninguna entidad.

¿Sigue funcionando el proyecto?

Gracias

**Comment by Danieldiazi** [comment]
Hola! Gracias por escribir.
Sigue funcionando el proyecto.
He probado a borrarla, para instalar desde cero por replicar tus pasos y parece que sigue yendo:
![imagen](https://github.com/Danieldiazi/homeassistant-meteogalicia_tides/assets/3638478/34ef4aec-b835-41cb-8983-d4dd54cdc6db)
y:

![imagen](https://github.com/Danieldiazi/homeassistant-meteogalicia_tides/assets/3638478/4eab52f3-0a2a-4096-a16f-df7afcfd44fb)
Entiendo que en el yaml de configuración has puesto algún puerto?

por ejemplo:
`sensor:
  - platform: meteogalicia_tides
    id_port: 3
    scan_interval: 1200
  - platform: meteogalicia_tides
    id_port: 2
    scan_interval: 1800`



Si puedes darme más info genial.

**Comment by diego-de-sousa** [comment]
Tengo exactamente como tú el puerto:

sensor:
  platform: meteogalicia_tides
  id_port: 3
  scan_interval: 1200
  
  He probado a borrar el sensor en la configuración, el paquete de HACS. Reiniciar HA. Volver a instalar, añadir la config. Reiniciar. No me vuelve a aparecer la entidad. ¿Tú la borraste? ¿O sólo borraste la integración?

**Comment by Danieldiazi** [comment]
La unica diferencia contigo es que yo lo tenia instalado pero ninguna entrada en la configuración. Asi que desinstalé, reinicié, instalé, metí entrada en configuración y volví a reiniciar.

Si puedes después de desinstalar (incluido quitar la entrada de configuración ), reinicia ( no deberia ser necesario pero por probar)

Luego, cuando instales , configures y despues del reinicio, mira los logs y filtra por "tides" a ver qué mensaje te aparece. Si puedes compartelo por aquí

**Comment by diego-de-sousa** [comment]
Vale, solucionado!

No tenía que ver con ese proceso si no con que tenía varias líneas de sensor en la configuración, en vez de tener una sección "sensor" con todas las "platforms". Disculpa el lío y muchas gracias por tu ayuda y la integración.

PD: No sé si es posible o lo pensaste pero molaría bastante tener un widget en el que se vean las mareas de 24h o algo así. Lo digo porque tengo uno para el sol/luna que me encanta. Supongo que es complejo.
![Captura de pantalla 2024-06-21 a las 14 05 23](https://github.com/Danieldiazi/homeassistant-meteogalicia_tides/assets/6465435/ee757de4-b008-48fe-bdea-dff8acfc9359)

PD2: Me encontré con esto que creo que me podría solucionar lo que te comento: https://github.com/jugla/worldtidesinfocustom

**Comment by Danieldiazi** [comment]
@cozarkd  Me alegro que todo se haya solucionado!  Tiene buena pinta lo que comentas. La del sol/luna la conocía y está muy chula. El otro enlace que comentas muy interesante.

**Comment by Danieldiazi** [comment]
Cierro, ya que está solucionado.
